### ISSUE TITLE
Settings should be saved on the keychain rather than in the user defaults

### ISSUE THREAD

**Issue by valeriomazzeo** [venmo/VENTouchLock#37]
It's very easy to reset the attempt history of failed passcode attempt and also to disable the use of touchid.

I would suggest to store this information inside the keychain of the device.

**Comment by dasmer** [comment]
Thanks @valeriomazzeo for pointing this out! I'll create a PR to move these into keychain soon.

**Comment by dasmer** [comment]
Closing this since it'll be fixed in 2.0

**Comment by chrisballinger** [comment]
@dasmer Any ETA on the fix? This is a huge security flaw.
