### ISSUE TITLE
We would like to help

### ISSUE THREAD

**Issue by ericlewis** [venmo/VENTouchLock#61]
Hate to leave an issue for this, but the chime team (myself and zinthemoney) would love to tack on and help develop some possible 2.0 features. It would be really nice to do some localization for 2.0. We also have a few other ideas. But it would be nice to have either a public thread or a way for us to contribute our ideas. :)

**Comment by dasmer** [comment]
:octocat: @ericlewis  Thanks for reaching out. PR's are welcome :)
