### ISSUE TITLE
Version 1.12.0 inaccessible 

### ISSUE THREAD

**Issue by Pearapps** [venmo/VENTouchLock#76]
Version 1.12.0 is not on cocoapods trunk: https://cocoapods.org/?q=ventouch - the latest version is 1.11.0 there.

**Comment by cyle** [comment]
help

**Comment by Pearapps** [comment]
Bump @dasmer

**Comment by Pearapps** [comment]
Bump @dasmer

**Comment by hyperspacemark** [comment]
@Pearapps Should be good now. Sorry for the inconvenience!

**Comment by Pearapps** [comment]
No worries thank you @hyperspacemark!
