### ISSUE TITLE
Replace SSKeychain with SAMKeychain

### ISSUE THREAD

**Issue by valeriomazzeo** [venmo/VENTouchLock#82]
`SSkeychain` is now deprecated and it should be replaced with `SAMKeychain`

**Comment by dasmer** [comment]
@valeriomazzeo Pull Requests are welcome!

**Comment by valeriomazzeo** [comment]
@dasmer thank you for fixing this, can you please push `1.13.0` to Cocoapods?

**Comment by ericlewis** [comment]
@valeriomazzeo it should already be pushed.

**Comment by valeriomazzeo** [comment]
@ericlewis 
On [Cocoapods](https://cocoapods.org/pods/VENTouchLock) is still `1.12.0`. Have you ran `pod trunk push`?

**Comment by valeriomazzeo** [comment]
@ericlewis I think you have forgotten to tag the commit with 1.13
