### ISSUE TITLE
Disabling touch id

### ISSUE THREAD

**Issue by filipealva** [venmo/VENTouchLock#86]
After trying 3 times with a invalid finger print VENTouchLock disabled the TouchID option (`canUseTouchId` some how was set to false even considering that I'm testing it in an iPhone 6s)

Any idea about how to fix it?

**Comment by filipealva** [comment]
Update: It seems that my iPhone invalidated the use of TouchID. I've blocked the screen and it asked for my passcode to reactivate touch id.

There is any chance that VENTouchLock caused it? I've never had this kind of experience using other apps.

**Comment by ericlewis** [comment]
No. This is at an OS level.
